const $ = id => document.getElementById(id);
let selected = new URLSearchParams(location.search).get('request') || localStorage.getItem('lab-selected'), activeTab = 'chat', traceData = null, requests = [], dbData = null;
let controls = {paused:true, network_fault:false}, busy = false, polling = false, lastAnswer = '';
const text = (tag, value, cls) => { const e=document.createElement(tag); e.textContent=value; if(cls)e.className=cls; return e; };
const pretty = value => JSON.stringify(value, null, 2);
const short = value => value ? value.slice(0,8) : '—';
// Refresh evidence without moving the reader's vertical or horizontal position.
function preserveScroll(root, update){
  const positions=new Map();
  const elements=()=>{const counts=new Map();return [root,...root.querySelectorAll('*')].map((el,i)=>{const label=el.id|| (el.tagName==='PRE'?el.parentElement.querySelector('.panel-heading')?.textContent:null)||String(i);const n=counts.get(label)||0;counts.set(label,n+1);return [label+':'+n,el];});};
  elements().forEach(([key,el])=>positions.set(key,[el.scrollTop,el.scrollLeft]));
  update();
  elements().forEach(([key,el])=>{const position=positions.get(key);if(position){el.scrollTop=position[0];el.scrollLeft=position[1];}});
}
function replaceEvidence(root,...children){preserveScroll(root,()=>root.replaceChildren(...children));}
async function api(path, body) {
  const response = await fetch(path, body === undefined ? {} : {method:'POST',headers:{'Content-Type':'application/json','X-Lab-Action':'1'},body:JSON.stringify(body)});
  const data = await response.json();
  if(!response.ok) throw new Error(typeof data.detail==='string' ? data.detail : pretty(data.detail||data));
  return data;
}
function notify(message, error=false){ $('toast').textContent=message; $('toast').hidden=false; if(error){$('error-banner').textContent=message;$('error-banner').hidden=false;} setTimeout(()=>$('toast').hidden=true,6500); }
function card(title, value, file='', wide=false){const el=text('div','',`panel${wide?' wide':''}`);el.append(text('div',title,'panel-heading'));if(file)el.append(text('div',file,'evidence-file mono'));el.append(text('pre',typeof value==='string'?value:pretty(value)));return el;}
function switchTab(tab){activeTab=tab;document.querySelectorAll('.tab-panel').forEach(e=>e.classList.toggle('active',e.id==='tab-'+tab));document.querySelectorAll('nav [data-tab]').forEach(e=>e.classList.toggle('active',e.dataset.tab===tab));const titles={chat:'Follow every token.',trace:'Under the hood.',databases:'Evidence, row by row.',lago:'From tokens to billing.',audit:'Trust, then verify.',settings:'Your local control room.'};$('page-title').textContent=titles[tab];if(tab==='databases')loadDB();if(tab==='lago')loadLago();if(tab==='audit')loadAudit();if(tab==='settings')loadSettings();}
document.querySelectorAll('[data-tab]').forEach(e=>e.addEventListener('click',()=>switchTab(e.dataset.tab)));
document.querySelectorAll('[data-prompt]').forEach(e=>e.addEventListener('click',()=>{$('prompt').value=e.dataset.prompt;$('prompt').focus();}));
function updateControls(){ $('mode-badge').textContent=controls.network_fault?'Delivery fault enabled':controls.paused?'Delivery paused':'Automatic delivery';$('mode-badge').className='badge '+(controls.network_fault?'red':controls.paused?'amber':'');$('exporter-mode').textContent=controls.network_fault?'Fault injected':controls.paused?'Paused':'Running';$('toggle-auto').textContent=controls.paused?'Resume':'Pause';$('toggle-fault').textContent=controls.network_fault?'Restore delivery':'Enable fault'; }
async function loadSettings(){try{const data=await api('/api/settings');controls=data.control;updateControls();$('settings-json').textContent=pretty(data);}catch(e){notify(e.message,true);}}
async function loadStatus(){try{const data=await api('/api/status');controls=data.control;updateControls();$('pending-count').textContent=data.billing.pending??'—';$('ack-count').textContent=data.billing.events_acknowledged_today??'—';$('dead-count').textContent=data.billing.counts?.dead_letters_open??'—';$('status-json').textContent=pretty(data);$('updated').textContent='Live evidence · '+new Date().toLocaleTimeString();}catch(e){$('updated').textContent='Status unavailable: '+e.message;}}
async function loadServices(){try{const data=await api('/api/services');$('services').replaceChildren(...data.map(s=>{const e=text('span',s.name,s.ok?'':'down');e.prepend(text('i','','dot'));return e;}));}catch(e){$('services').textContent='Service checks unavailable';}}
async function loadHistory(){requests=await api('/api/requests');replaceEvidence($('history'),...requests.map(r=>{const b=text('button','',r.id===selected?'selected':'');b.append(text('span',r.prompt,'history-prompt'),text('small',`${short(r.id)} · ${r.customer} · ${r.status}`));b.addEventListener('click',()=>select(r.id));return b;}));if(!requests.length)$('history').append(text('p','No requests yet.'));if(document.activeElement!==$('selected-request')){const empty=text('option','Select a recorded request…');empty.value='';$('selected-request').replaceChildren(empty,...requests.map(r=>{const o=text('option',`${short(r.id)} · ${r.customer} · ${r.prompt.slice(0,70)}`);o.value=r.id;return o;}));$('selected-request').value=selected||'';}}
$('selected-request').addEventListener('change',()=>{if($('selected-request').value)select($('selected-request').value);});
async function select(id){selected=id;localStorage.setItem('lab-selected',id);lastAnswer='';await loadTrace();await loadHistory();}
function renderConversation(r){if(!r)return;const c=$('conversation'), nearBottom=c.scrollHeight-c.scrollTop-c.clientHeight<100;const u=text('div','','message user');u.append(text('small','You · '+r.customer+' / '+r.provider),text('div',r.prompt,'text'));const a=text('div','','message assistant');a.append(text('small','Llama 3.2 · '+r.status),text('div',r.answer|| (r.status==='queued'?'Queued for local inference…':'Loading Llama and generating…'),'text'));if(r.error)a.append(text('p',r.error,'generating'));if(r.usage){const strip=text('div','','usage-strip');strip.append(text('span',r.usage.prompt_tokens+' input'),text('span',r.usage.completion_tokens+' output'),text('span',r.finish_reason==='length'?'Output limit reached':'Stream complete'));a.append(strip);}c.replaceChildren(u,a);if(nearBottom||lastAnswer==='')c.scrollTop=c.scrollHeight;lastAnswer=r.answer;}
function renderPipeline(data){const r=data?.request, rows=data?.rows||[], first=rows[0], delivery=first?.delivery, terminal=first?.terminal;const acknowledged=rows.reduce((n,x)=>n+x.acknowledgements.length,0), expected=rows.reduce((n,x)=>n+x.expected_events.length,0);const remote=data?.lago_events?.length||0;const stages=[
  ['Request received',r?`${short(r.id)} · ${r.customer}`:'Waiting for a prompt',!!r],
  ['Llama inference',r?.status==='completed'?`${r.usage?.completion_tokens??'?'} output tokens`:r?.status||'Local Ollama runtime',r?.status==='completed',r?.status==='error'],
  ['GoModel usage persisted',first?`${rows.length} row(s) · ${short(first.source.id)}`:'Waiting for the usage buffer to flush',!!first],
  ['Mapped & frozen',delivery?`${delivery.payload.subscription_id} · pending=${delivery.pending}`:first?.mapping.reason||'No delivery intent yet',!!delivery,first&&first.mapping.outcome!=='mapped'],
  ['Exporter acknowledged',terminal?`${terminal.status} · ${acknowledged} event acknowledgements`:'No terminal result yet',terminal?.status==='sent',terminal&&terminal.status!=='sent'],
  ['Lago events observed',data?.lago_error?'Unavailable: '+data.lago_error:`${remote} of ${expected} expected events`,expected>0&&remote===expected,!!data?.lago_error]
];$('pipeline').replaceChildren(...stages.map(([title,detail,done,warn],i)=>{const e=text('div','',`stage ${done?'complete':warn?'warning':''}`),body=text('div','');body.append(text('strong',title),text('small',detail));e.append(text('span',done?'✓':String(i+1),'stage-icon'),body);return e;}));}
function renderTrace(data){traceData=data;const r=data.request;renderConversation(r);renderPipeline(data);$('trace-short').textContent=short(r.id);$('selected-description').textContent=`${r.id} · ${r.customer} · ${r.provider} · ${r.created_at}`;const summary=$('trace-summary');summary.replaceChildren(text('span','Request '+r.status,'badge'),text('span',data.rows.length+' source rows','badge'),text('span',data.lago_events.length+' Lago events','badge'));if(data.lago_error)summary.append(text('span','Lago unavailable','badge red'));const content=$('trace-content');const refresh=()=>{content.replaceChildren(card('01 / Browser → GoModel',r.http_body,'demo/live_app.py → POST /v1/chat/completions'),card('02 / Model response & measured usage',{answer:r.answer,usage:r.usage,response_id:r.response_id,finish_reason:r.finish_reason,http_status:r.http_status},'GoModel → Ollama → streaming response'));
data.rows.forEach((row,i)=>{content.append(card(`03 / PostgreSQL source row ${i+1}`,row.source,'exporter/reader.py → UsageRow'),card('04 / Mapping & token split',{mapping:row.mapping,segments:row.segments,expected_events:row.expected_events},'exporter/mapper.py + exporter/events.py'),card('05 / Frozen delivery',row.delivery||'Not prepared yet. Click “Prepare only”.','exporter/delivery.py + exporter/state/store.py'),card('06 / Acknowledgements & terminal state',{acknowledgements:row.acknowledgements,terminal:row.terminal,dead_letters:row.dead_letters},'exporter/runner.py → state transaction'));});content.append(card('07 / Lago events returned by the API',data.lago_error?{unavailable:data.lago_error}:data.lago_events,'exporter/lago_read.py → GET /api/v1/events',true),card('08 / Delivery attempts & actual HTTP exchanges',r.delivery_attempts||'Click Deliver / replay to record HTTP status codes and request/response bodies here. Authentication headers are excluded.','exporter/sender.py + exporter/lago_client.py',true));if(!data.rows.length)summary.append(text('span','Waiting for GoModel persistence','badge amber'));};preserveScroll(content,refresh);}
async function loadTrace(){if(!selected){renderPipeline(null);return;}try{renderTrace(await api('/api/requests/'+selected));}catch(e){if(e.message==='Request not found'){selected=null;localStorage.removeItem('lab-selected');}else notify(e.message,true);}}
$('chat-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;$('error-banner').hidden=true;$('send').disabled=true;try{const r=await api('/api/requests',{prompt:$('prompt').value,customer:$('customer').value,provider:$('provider').value,max_tokens:Number($('max-tokens').value),temperature:Number($('temperature').value)});$('prompt').value='';await select(r.id);}catch(e){notify(e.message,true);}finally{$('send').disabled=false;}});
async function act(action){if(!selected){notify('Send or select a request first.');return;}if(busy)return;busy=true;const buttons=document.querySelectorAll('[data-action]');buttons.forEach(b=>b.disabled=true);notify(action==='reconcile'?'Reading source, state and Lago evidence…':'Running '+action+' through the exporter…');try{const result=await api(`/api/requests/${selected}/${action}`,{});if(action==='reconcile'){switchTab('audit');$('audit-content').prepend(card('Just completed: '+result.status,result));notify('Reconciliation: '+result.status);}else notify(result.reports?.map(x=>x.summary).join(' ')||result.note);await loadTrace();await loadStatus();}catch(e){notify(e.message,true);}finally{busy=false;buttons.forEach(b=>b.disabled=false);}}
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>act(b.dataset.action)));
const tables={source:['usage'],state:['deliveries','usage_rows','event_acknowledgements','dead_letters','export_cursor','worker_status','reconciliation_runs']};
$('db').addEventListener('change',()=>{$('table').replaceChildren(...tables[$('db').value].map(t=>{const o=text('option',t);o.value=t;return o;}));loadDB();});$('table').addEventListener('change',loadDB);
const display=v=>typeof v==='object'?JSON.stringify(v):String(v??'null');
function makeTable(rows,columns,onSelect){const table=document.createElement('table'),head=document.createElement('thead'),tr=document.createElement('tr');columns.forEach(k=>tr.append(text('th',k)));head.append(tr);table.append(head);const body=document.createElement('tbody');rows.forEach(row=>{const tr=document.createElement('tr');columns.forEach(k=>{const td=text('td',display(row[k]));td.title=display(row[k]);tr.append(td);});if(onSelect)tr.addEventListener('click',()=>onSelect(row));body.append(tr);});table.append(body);return table;}
function renderDB(){if(!dbData)return;const query=$('db-filter').value.toLowerCase();const rows=dbData.rows.filter(r=>pretty(r).toLowerCase().includes(query));const keys=Object.keys(dbData.rows[0]||{}).slice(0,9);replaceEvidence($('db-table'),rows.length?makeTable(rows,keys,r=>$('db-row').textContent=pretty(r)):text('div','No matching rows.','empty'));$('db-title').textContent=`${dbData.database} / ${dbData.table} · ${rows.length} shown of ${dbData.total} total (latest 100)`;$('db-query').textContent=dbData.query;replaceEvidence($('db-schema'),makeTable(dbData.columns,['column_name','data_type','is_nullable']));}
async function loadDB(){try{dbData=await api(`/api/database/${$('db').value}/${$('table').value}`);renderDB();}catch(e){notify(e.message,true);}}
$('db-filter').addEventListener('input',renderDB);$('filter-selected').addEventListener('click',()=>{const id=traceData?.rows[0]?.source.id;if(!id){notify('Selected request has no persisted usage yet.');return;}$('db-filter').value=id;renderDB();});
async function loadLago(){try{const d=await api('/api/lago');replaceEvidence($('lago-content'),card('Selected request / stored events',traceData?.lago_error?{unavailable:traceData.lago_error}:traceData?.lago_events||[],'GET /api/v1/events',true),card('Acme / current Llama billing usage',d.usage.sub_acme,'GET /api/v1/customers/acme/current_usage'),card('Beta / current Llama billing usage',d.usage.sub_beta,'GET /api/v1/customers/beta/current_usage'),card('Metric definitions',d.metrics,'GET /api/v1/billable_metrics'),card('Active subscriptions',d.subscriptions,'GET /api/v1/subscriptions/{id}'),card('Plan & model pricing',d.plan,'GET /api/v1/plans/llm_usage',true));}catch(e){replaceEvidence($('lago-content'),card('Lago evidence unavailable',e.message));}}
async function loadAudit(){try{const d=await api('/api/database/state/reconciliation_runs');replaceEvidence($('audit-content'),...d.rows.slice(0,10).map(r=>card(`${r.status} · ${r.period_start} → ${r.period_end}`,r.report,'exporter/reconcile.py → reconciliation_runs')));if(!d.rows.length)$('audit-content').append(card('No audits yet','Select a completed request and click reconcile. Allow at least 2 seconds after delivery.'));}catch(e){notify(e.message,true);}}
async function setControl(next){try{controls=await api('/api/control',next);updateControls();await loadSettings();notify(controls.paused?'Automatic delivery paused.':'Automatic delivery resumed.');}catch(e){notify(e.message,true);}}
$('toggle-auto').addEventListener('click',()=>setControl({...controls,paused:!controls.paused}));$('toggle-fault').addEventListener('click',()=>setControl({...controls,network_fault:!controls.network_fault}));$('cycle').addEventListener('click',async()=>{try{notify((await api('/api/cycle',{})).summary);await loadTrace();await loadStatus();}catch(e){notify(e.message,true);}});
$('refresh-history').addEventListener('click',()=>loadHistory().catch(e=>notify(e.message,true)));$('refresh-trace').addEventListener('click',loadTrace);$('refresh-db').addEventListener('click',loadDB);$('refresh-lago').addEventListener('click',loadLago);$('refresh-audit').addEventListener('click',loadAudit);$('max-tokens').addEventListener('change',()=>$('token-limit-label').textContent=$('max-tokens').value);
async function poll(){if(polling||document.hidden)return;polling=true;try{await Promise.all([loadTrace(),loadStatus(),loadHistory()]);if(activeTab==='databases')await loadDB();}catch(e){$('updated').textContent='Connection interrupted · retrying';}finally{polling=false;}}
loadSettings();loadServices();renderPipeline(null);poll();setInterval(poll,1800);setInterval(loadServices,15000);
